language: node_js
env:
  global:
  - NODE_ENV=production
  - NPM_CONFIG_PRODUCTION=false
  - NETLIFY_APP=6f74c339-35c4-4f10-be35-853231c234c2
  - secure: cAguMZkeYs6wmpNNZHKjen5j/GhtXtp0XKh7bhViQ7FOOhnsTKVTy1JfSmNkWTtGCIerZKssQPEHPMYAtHITYOMpqAYd/Da8gSvpAep9RPqUMiqejyE71fkc4D4S0VMPZfySn8/R8rCpuHSLb8Agr4WonA8Bq663B6oe7LFyv5OCQZbAbqp3/S5U2Fnc11KfLruw448abbWrpzc8oSCaAJrA60AcVfP/MOziD0tW6OXRP6EA8ea6/kTHhDCio9/K6YlXU2qu54NwYAi9u2U9Cp+c71edG8PManAI53jC6zwsHki7pfS+ekcdsT1sSzpm182aoDpZRGV7jxaNXI+NxhaSEiOfwoF7j7bLsG2BRepjODM/d5wNtQ9k7+jSdK9lNmIfeOnjLafvBceTRTSGwbrhfgcGvNbdIx6NWJ8UmF5p4FpFopHOmavsE1QD6vb4jD1xMJUuAKqEpxvzmmEi6SOo8KBtjlneWIKaai84HtoxE65S6eSeudpfpVFRo81YrnVkkOQU5+C5dwJ4jCJVw16gXSvN4fZb2lH4ovoSvkvUUDFDboVupSI0oVCx9seTa4sEZBKporWiOA+b8fLKIAK42zt65oSsum6vbn/NlLndigf8PvJsitThxsWMtBLwnul/GEPdVcJ0TO1Gp/zn3mMznJOs3vYJZ6dwh6WsdL0=
before_deploy: chmod +x ./deploy_static.sh
deploy:
  - provider: heroku
    api_key:
      secure: NmoXgP9XdGcEuGhrvUlzmi9w0l0+TqByseHFrT1t7Qa7MoxOSBsc/75/EExGq4c8bka5gBjfBQ7/gRVbZlvgT4HWuIKn0A1zXtctWEDDyilE1i12oN5r6sPWSZm5R+1mzgcbg7YaXu7VbLIyCFy429mZXfWNh2KpgDsGcWNOfr98a3rcKeCzbJ4ac7E4Bo/Gp88bynXXsS+tl8lE1Ro0F6uF/aMPN9evyMDmJXM0w/IlYQTcn9JdZNjWoOdI36GvatwLcZxi2n2MsQB9rOMnmAN4N66vqi04dzvqM5CHVLMkZlzfJv/hJDNm8cjA2qQfDkcZq2A/qpY9g2hqrIfMxIW9Wvet+NJBbYEG9ijXGKiUzFQ/MFBYRtMaZjJp4GQD+fX0cjOMHOFEPEx5U+yWfdYwgEz+um8OHBUf2TomoQYptQKqvgKFnZ7G/nQ608UptxmGjcZBKMqmNSYR/xzEtIhnIDBhpAx6sOiaD6yQU0tuqzcleokXX1idr+QQeIbVOl8FOVs1EogrUBbW+3puyZGb4+Rtyo9E5Gj8s/K9YyXOeu67k8RkP4Hcm8G2CjaZGvkONkyMcYCQeZocVpHezpUWpTfOzzSpwWVqCZVQYPB5eutqG9eAg7Pq0h7TfdKgN+SpTf2FNS2pBwtY7gSuhHYn3SYd17xP60+66fCWCo0=
    app:
      master: secret-earth-30212
    skip_cleanup: true
  - provider: script
    script: ./deploy_static.sh
    skip_cleanup: true
    on:
      branch: master
